/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as CdnsRouteImport } from './routes/cdns'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperationIndexRouteImport } from './routes/operation/index'
import { Route as MitigationIndexRouteImport } from './routes/mitigation/index'
import { Route as MitigationWhitelistRouteImport } from './routes/mitigation/whitelist'
import { Route as MitigationFlowspecRouteImport } from './routes/mitigation/flowspec'
import { Route as MitigationBlacklistRouteImport } from './routes/mitigation/blacklist'
import { Route as MitigationBgpRouteImport } from './routes/mitigation/bgp'
import { Route as MitigationActiveRouteImport } from './routes/mitigation/active'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CdnsRoute = CdnsRouteImport.update({
  id: '/cdns',
  path: '/cdns',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationIndexRoute = OperationIndexRouteImport.update({
  id: '/operation/',
  path: '/operation/',
  getParentRoute: () => rootRouteImport,
} as any)
const MitigationIndexRoute = MitigationIndexRouteImport.update({
  id: '/mitigation/',
  path: '/mitigation/',
  getParentRoute: () => rootRouteImport,
} as any)
const MitigationWhitelistRoute = MitigationWhitelistRouteImport.update({
  id: '/mitigation/whitelist',
  path: '/mitigation/whitelist',
  getParentRoute: () => rootRouteImport,
} as any)
const MitigationFlowspecRoute = MitigationFlowspecRouteImport.update({
  id: '/mitigation/flowspec',
  path: '/mitigation/flowspec',
  getParentRoute: () => rootRouteImport,
} as any)
const MitigationBlacklistRoute = MitigationBlacklistRouteImport.update({
  id: '/mitigation/blacklist',
  path: '/mitigation/blacklist',
  getParentRoute: () => rootRouteImport,
} as any)
const MitigationBgpRoute = MitigationBgpRouteImport.update({
  id: '/mitigation/bgp',
  path: '/mitigation/bgp',
  getParentRoute: () => rootRouteImport,
} as any)
const MitigationActiveRoute = MitigationActiveRouteImport.update({
  id: '/mitigation/active',
  path: '/mitigation/active',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/cdns': typeof CdnsRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/mitigation/active': typeof MitigationActiveRoute
  '/mitigation/bgp': typeof MitigationBgpRoute
  '/mitigation/blacklist': typeof MitigationBlacklistRoute
  '/mitigation/flowspec': typeof MitigationFlowspecRoute
  '/mitigation/whitelist': typeof MitigationWhitelistRoute
  '/mitigation/': typeof MitigationIndexRoute
  '/operation/': typeof OperationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/cdns': typeof CdnsRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/mitigation/active': typeof MitigationActiveRoute
  '/mitigation/bgp': typeof MitigationBgpRoute
  '/mitigation/blacklist': typeof MitigationBlacklistRoute
  '/mitigation/flowspec': typeof MitigationFlowspecRoute
  '/mitigation/whitelist': typeof MitigationWhitelistRoute
  '/mitigation': typeof MitigationIndexRoute
  '/operation': typeof OperationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/cdns': typeof CdnsRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/mitigation/active': typeof MitigationActiveRoute
  '/mitigation/bgp': typeof MitigationBgpRoute
  '/mitigation/blacklist': typeof MitigationBlacklistRoute
  '/mitigation/flowspec': typeof MitigationFlowspecRoute
  '/mitigation/whitelist': typeof MitigationWhitelistRoute
  '/mitigation/': typeof MitigationIndexRoute
  '/operation/': typeof OperationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/cdns'
    | '/change-password'
    | '/dashboard'
    | '/events'
    | '/login'
    | '/mitigation/active'
    | '/mitigation/bgp'
    | '/mitigation/blacklist'
    | '/mitigation/flowspec'
    | '/mitigation/whitelist'
    | '/mitigation/'
    | '/operation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/cdns'
    | '/change-password'
    | '/dashboard'
    | '/events'
    | '/login'
    | '/mitigation/active'
    | '/mitigation/bgp'
    | '/mitigation/blacklist'
    | '/mitigation/flowspec'
    | '/mitigation/whitelist'
    | '/mitigation'
    | '/operation'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/cdns'
    | '/change-password'
    | '/dashboard'
    | '/events'
    | '/login'
    | '/mitigation/active'
    | '/mitigation/bgp'
    | '/mitigation/blacklist'
    | '/mitigation/flowspec'
    | '/mitigation/whitelist'
    | '/mitigation/'
    | '/operation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  CdnsRoute: typeof CdnsRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  DashboardRoute: typeof DashboardRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  MitigationActiveRoute: typeof MitigationActiveRoute
  MitigationBgpRoute: typeof MitigationBgpRoute
  MitigationBlacklistRoute: typeof MitigationBlacklistRoute
  MitigationFlowspecRoute: typeof MitigationFlowspecRoute
  MitigationWhitelistRoute: typeof MitigationWhitelistRoute
  MitigationIndexRoute: typeof MitigationIndexRoute
  OperationIndexRoute: typeof OperationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cdns': {
      id: '/cdns'
      path: '/cdns'
      fullPath: '/cdns'
      preLoaderRoute: typeof CdnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operation/': {
      id: '/operation/'
      path: '/operation'
      fullPath: '/operation/'
      preLoaderRoute: typeof OperationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitigation/': {
      id: '/mitigation/'
      path: '/mitigation'
      fullPath: '/mitigation/'
      preLoaderRoute: typeof MitigationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitigation/whitelist': {
      id: '/mitigation/whitelist'
      path: '/mitigation/whitelist'
      fullPath: '/mitigation/whitelist'
      preLoaderRoute: typeof MitigationWhitelistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitigation/flowspec': {
      id: '/mitigation/flowspec'
      path: '/mitigation/flowspec'
      fullPath: '/mitigation/flowspec'
      preLoaderRoute: typeof MitigationFlowspecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitigation/blacklist': {
      id: '/mitigation/blacklist'
      path: '/mitigation/blacklist'
      fullPath: '/mitigation/blacklist'
      preLoaderRoute: typeof MitigationBlacklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitigation/bgp': {
      id: '/mitigation/bgp'
      path: '/mitigation/bgp'
      fullPath: '/mitigation/bgp'
      preLoaderRoute: typeof MitigationBgpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitigation/active': {
      id: '/mitigation/active'
      path: '/mitigation/active'
      fullPath: '/mitigation/active'
      preLoaderRoute: typeof MitigationActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  CdnsRoute: CdnsRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  DashboardRoute: DashboardRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  MitigationActiveRoute: MitigationActiveRoute,
  MitigationBgpRoute: MitigationBgpRoute,
  MitigationBlacklistRoute: MitigationBlacklistRoute,
  MitigationFlowspecRoute: MitigationFlowspecRoute,
  MitigationWhitelistRoute: MitigationWhitelistRoute,
  MitigationIndexRoute: MitigationIndexRoute,
  OperationIndexRoute: OperationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
