/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemRouteImport } from './routes/system'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as CdnsRouteImport } from './routes/cdns'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperationIndexRouteImport } from './routes/operation/index'
import { Route as MitigationIndexRouteImport } from './routes/mitigation/index'
import { Route as OperationThresholdsRouteImport } from './routes/operation/thresholds'
import { Route as OperationCollectorsRouteImport } from './routes/operation/collectors'
import { Route as OperationBgpSessionsRouteImport } from './routes/operation/bgp-sessions'
import { Route as MitigationWhitelistRouteImport } from './routes/mitigation/whitelist'
import { Route as MitigationPolicyRouteImport } from './routes/mitigation/policy'
import { Route as MitigationFlowspecRouteImport } from './routes/mitigation/flowspec'
import { Route as MitigationBlacklistRouteImport } from './routes/mitigation/blacklist'
import { Route as MitigationBgpRouteImport } from './routes/mitigation/bgp'
import { Route as MitigationActiveRouteImport } from './routes/mitigation/active'

const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CdnsRoute = CdnsRouteImport.update({
  id: '/cdns',
  path: '/cdns',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationIndexRoute = OperationIndexRouteImport.update({
  id: '/operation/',
  path: '/operation/',
  getParentRoute: () => rootRouteImport,
} as any)
const MitigationIndexRoute = MitigationIndexRouteImport.update({
  id: '/mitigation/',
  path: '/mitigation/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationThresholdsRoute = OperationThresholdsRouteImport.update({
  id: '/operation/thresholds',
  path: '/operation/thresholds',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationCollectorsRoute = OperationCollectorsRouteImport.update({
  id: '/operation/collectors',
  path: '/operation/collectors',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationBgpSessionsRoute = OperationBgpSessionsRouteImport.update({
  id: '/operation/bgp-sessions',
  path: '/operation/bgp-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const MitigationWhitelistRoute = MitigationWhitelistRouteImport.update({
  id: '/mitigation/whitelist',
  path: '/mitigation/whitelist',
  getParentRoute: () => rootRouteImport,
} as any)
const MitigationPolicyRoute = MitigationPolicyRouteImport.update({
  id: '/mitigation/policy',
  path: '/mitigation/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MitigationFlowspecRoute = MitigationFlowspecRouteImport.update({
  id: '/mitigation/flowspec',
  path: '/mitigation/flowspec',
  getParentRoute: () => rootRouteImport,
} as any)
const MitigationBlacklistRoute = MitigationBlacklistRouteImport.update({
  id: '/mitigation/blacklist',
  path: '/mitigation/blacklist',
  getParentRoute: () => rootRouteImport,
} as any)
const MitigationBgpRoute = MitigationBgpRouteImport.update({
  id: '/mitigation/bgp',
  path: '/mitigation/bgp',
  getParentRoute: () => rootRouteImport,
} as any)
const MitigationActiveRoute = MitigationActiveRouteImport.update({
  id: '/mitigation/active',
  path: '/mitigation/active',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/audit': typeof AuditRoute
  '/cdns': typeof CdnsRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/mitigation/active': typeof MitigationActiveRoute
  '/mitigation/bgp': typeof MitigationBgpRoute
  '/mitigation/blacklist': typeof MitigationBlacklistRoute
  '/mitigation/flowspec': typeof MitigationFlowspecRoute
  '/mitigation/policy': typeof MitigationPolicyRoute
  '/mitigation/whitelist': typeof MitigationWhitelistRoute
  '/operation/bgp-sessions': typeof OperationBgpSessionsRoute
  '/operation/collectors': typeof OperationCollectorsRoute
  '/operation/thresholds': typeof OperationThresholdsRoute
  '/mitigation/': typeof MitigationIndexRoute
  '/operation/': typeof OperationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/audit': typeof AuditRoute
  '/cdns': typeof CdnsRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/mitigation/active': typeof MitigationActiveRoute
  '/mitigation/bgp': typeof MitigationBgpRoute
  '/mitigation/blacklist': typeof MitigationBlacklistRoute
  '/mitigation/flowspec': typeof MitigationFlowspecRoute
  '/mitigation/policy': typeof MitigationPolicyRoute
  '/mitigation/whitelist': typeof MitigationWhitelistRoute
  '/operation/bgp-sessions': typeof OperationBgpSessionsRoute
  '/operation/collectors': typeof OperationCollectorsRoute
  '/operation/thresholds': typeof OperationThresholdsRoute
  '/mitigation': typeof MitigationIndexRoute
  '/operation': typeof OperationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/audit': typeof AuditRoute
  '/cdns': typeof CdnsRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/mitigation/active': typeof MitigationActiveRoute
  '/mitigation/bgp': typeof MitigationBgpRoute
  '/mitigation/blacklist': typeof MitigationBlacklistRoute
  '/mitigation/flowspec': typeof MitigationFlowspecRoute
  '/mitigation/policy': typeof MitigationPolicyRoute
  '/mitigation/whitelist': typeof MitigationWhitelistRoute
  '/operation/bgp-sessions': typeof OperationBgpSessionsRoute
  '/operation/collectors': typeof OperationCollectorsRoute
  '/operation/thresholds': typeof OperationThresholdsRoute
  '/mitigation/': typeof MitigationIndexRoute
  '/operation/': typeof OperationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/audit'
    | '/cdns'
    | '/change-password'
    | '/dashboard'
    | '/events'
    | '/login'
    | '/notifications'
    | '/settings'
    | '/system'
    | '/mitigation/active'
    | '/mitigation/bgp'
    | '/mitigation/blacklist'
    | '/mitigation/flowspec'
    | '/mitigation/policy'
    | '/mitigation/whitelist'
    | '/operation/bgp-sessions'
    | '/operation/collectors'
    | '/operation/thresholds'
    | '/mitigation/'
    | '/operation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/audit'
    | '/cdns'
    | '/change-password'
    | '/dashboard'
    | '/events'
    | '/login'
    | '/notifications'
    | '/settings'
    | '/system'
    | '/mitigation/active'
    | '/mitigation/bgp'
    | '/mitigation/blacklist'
    | '/mitigation/flowspec'
    | '/mitigation/policy'
    | '/mitigation/whitelist'
    | '/operation/bgp-sessions'
    | '/operation/collectors'
    | '/operation/thresholds'
    | '/mitigation'
    | '/operation'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/audit'
    | '/cdns'
    | '/change-password'
    | '/dashboard'
    | '/events'
    | '/login'
    | '/notifications'
    | '/settings'
    | '/system'
    | '/mitigation/active'
    | '/mitigation/bgp'
    | '/mitigation/blacklist'
    | '/mitigation/flowspec'
    | '/mitigation/policy'
    | '/mitigation/whitelist'
    | '/operation/bgp-sessions'
    | '/operation/collectors'
    | '/operation/thresholds'
    | '/mitigation/'
    | '/operation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  AuditRoute: typeof AuditRoute
  CdnsRoute: typeof CdnsRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  DashboardRoute: typeof DashboardRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  SettingsRoute: typeof SettingsRoute
  SystemRoute: typeof SystemRoute
  MitigationActiveRoute: typeof MitigationActiveRoute
  MitigationBgpRoute: typeof MitigationBgpRoute
  MitigationBlacklistRoute: typeof MitigationBlacklistRoute
  MitigationFlowspecRoute: typeof MitigationFlowspecRoute
  MitigationPolicyRoute: typeof MitigationPolicyRoute
  MitigationWhitelistRoute: typeof MitigationWhitelistRoute
  OperationBgpSessionsRoute: typeof OperationBgpSessionsRoute
  OperationCollectorsRoute: typeof OperationCollectorsRoute
  OperationThresholdsRoute: typeof OperationThresholdsRoute
  MitigationIndexRoute: typeof MitigationIndexRoute
  OperationIndexRoute: typeof OperationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cdns': {
      id: '/cdns'
      path: '/cdns'
      fullPath: '/cdns'
      preLoaderRoute: typeof CdnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operation/': {
      id: '/operation/'
      path: '/operation'
      fullPath: '/operation/'
      preLoaderRoute: typeof OperationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitigation/': {
      id: '/mitigation/'
      path: '/mitigation'
      fullPath: '/mitigation/'
      preLoaderRoute: typeof MitigationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operation/thresholds': {
      id: '/operation/thresholds'
      path: '/operation/thresholds'
      fullPath: '/operation/thresholds'
      preLoaderRoute: typeof OperationThresholdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operation/collectors': {
      id: '/operation/collectors'
      path: '/operation/collectors'
      fullPath: '/operation/collectors'
      preLoaderRoute: typeof OperationCollectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operation/bgp-sessions': {
      id: '/operation/bgp-sessions'
      path: '/operation/bgp-sessions'
      fullPath: '/operation/bgp-sessions'
      preLoaderRoute: typeof OperationBgpSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitigation/whitelist': {
      id: '/mitigation/whitelist'
      path: '/mitigation/whitelist'
      fullPath: '/mitigation/whitelist'
      preLoaderRoute: typeof MitigationWhitelistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitigation/policy': {
      id: '/mitigation/policy'
      path: '/mitigation/policy'
      fullPath: '/mitigation/policy'
      preLoaderRoute: typeof MitigationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitigation/flowspec': {
      id: '/mitigation/flowspec'
      path: '/mitigation/flowspec'
      fullPath: '/mitigation/flowspec'
      preLoaderRoute: typeof MitigationFlowspecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitigation/blacklist': {
      id: '/mitigation/blacklist'
      path: '/mitigation/blacklist'
      fullPath: '/mitigation/blacklist'
      preLoaderRoute: typeof MitigationBlacklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitigation/bgp': {
      id: '/mitigation/bgp'
      path: '/mitigation/bgp'
      fullPath: '/mitigation/bgp'
      preLoaderRoute: typeof MitigationBgpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitigation/active': {
      id: '/mitigation/active'
      path: '/mitigation/active'
      fullPath: '/mitigation/active'
      preLoaderRoute: typeof MitigationActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  AuditRoute: AuditRoute,
  CdnsRoute: CdnsRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  DashboardRoute: DashboardRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  SettingsRoute: SettingsRoute,
  SystemRoute: SystemRoute,
  MitigationActiveRoute: MitigationActiveRoute,
  MitigationBgpRoute: MitigationBgpRoute,
  MitigationBlacklistRoute: MitigationBlacklistRoute,
  MitigationFlowspecRoute: MitigationFlowspecRoute,
  MitigationPolicyRoute: MitigationPolicyRoute,
  MitigationWhitelistRoute: MitigationWhitelistRoute,
  OperationBgpSessionsRoute: OperationBgpSessionsRoute,
  OperationCollectorsRoute: OperationCollectorsRoute,
  OperationThresholdsRoute: OperationThresholdsRoute,
  MitigationIndexRoute: MitigationIndexRoute,
  OperationIndexRoute: OperationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
